/**
 * PRODUCT_TICKER — ~190 noms de produits cosmétiques TRÈS GRAND PUBLIC (marques
 * de super/hypermarché & pharmacie ultra-connues), servant de placeholder ANIMÉ
 * « machine à écrire » dans la barre de recherche du dashboard. Purement
 * décoratif : uniquement des noms de produits largement reconnus.
 */
export const PRODUCT_TICKER: readonly string[] = [
  // ── Visage : nettoyants & soins (grand public + pharmacie connue) ──
  'CeraVe Gel Nettoyant Moussant',
  'CeraVe Crème Hydratante',
  'La Roche-Posay Effaclar Duo+',
  'La Roche-Posay Cicaplast Baume B5',
  'La Roche-Posay Toleriane',
  'Bioderma Sensibio H2O',
  'Bioderma Sébium Gel Moussant',
  'Garnier SkinActive Eau Micellaire',
  'Garnier Vitamine C',
  'Nivea Eau Micellaire',
  'Nivea Crème',
  'Nivea Q10 Anti-Rides',
  'Neutrogena Hydro Boost',
  'Mixa Crème Anti-Sécheresse',
  'Avène Eau Thermale',
  'Avène Cleanance',
  'Vichy Normaderm',
  'Vichy Minéral 89',
  'Diadermine Lift+',
  'Embryolisse Lait-Crème',
  'Nuxe Huile Prodigieuse',
  'Nuxe Rêve de Miel',
  'Caudalie Eau de Beauté',
  'The Ordinary Niacinamide 10%',
  'Labello Original',
  'Homéoplasmine',
  'Vaseline',

  // ── Solaire ──
  'Nivea Sun Protect & Hydrate',
  'Garnier Ambre Solaire',
  'La Roche-Posay Anthelios',
  'Bioderma Photoderm',
  'Avène Solaire SPF50+',
  'Piz Buin Allergy',
  'Mixa Solaire Peau Sensible',

  // ── Corps & douche ──
  'Dove Gel Douche Nourrissant',
  'Dove Savon de Beauté',
  'Le Petit Marseillais Douche Karité',
  'Le Petit Marseillais Savon Liquide',
  'Sanex Zéro% Gel Douche',
  'Sanex Dermo Protector',
  'Tahiti Douche Fruit du Dragon',
  'Palmolive Gel Douche',
  'Fa Gel Douche Yoghurt',
  'Monsavon Lait & Miel',
  'Cadum Savon Surgras',
  'Nivea Lait Corps Hydratant',
  'Mixa Lait Corps Karité',
  'Le Chat Savon de Marseille',
  'Neutrogena Formule Norvégienne',
  'Cien Lait Corps',
  'Petit Marseillais Extra Doux',

  // ── Cheveux ──
  'Garnier Fructis Force Ultime',
  'Garnier Ultra Doux Miel & Fleurs',
  "L'Oréal Elsève Extraordinary Oil",
  "L'Oréal Elsève Total Repair 5",
  'Head & Shoulders Antipelliculaire',
  'Pantene Pro-V Réparateur',
  'Dop Shampooing Douceur',
  'Timotei Pur',
  'Schwarzkopf Gliss Kur',
  'Franck Provost Expert Repair',
  'Klorane Shampooing à l’Avoine',
  'Aussie Miracle Moist',
  'Ultra Doux Ricin & Amande',
  'Fructis Hydra Bouclettes',
  'Petrole Hahn',
  'Hask Masque Cheveux',

  // ── Déodorants ──
  'Nivea Deo Black & White',
  'Rexona Men Cobalt',
  'Dove Original Déodorant',
  'Narta Bille Fraîcheur',
  'Sanex Dermo Déodorant',
  'Etiaxil Détranspirant',
  'Axe Dark Temptation',
  'Mennen Déodorant',
  'Vichy Déodorant 48h',

  // ── Hygiène dentaire ──
  'Signal Intégral 8',
  'Colgate Total Original',
  'Sensodyne Répare & Protège',
  'Elmex Protection Caries',
  'Oral-B 3D White',
  'Fluocaril Bi-Fluoré',
  'Parodontax Fraîcheur',
  'Listerine Cool Mint',

  // ── Rasage & soins homme ──
  'Gillette Fusion5 Gel',
  'Wilkinson Hydro 5',
  'Nivea Men Sensitive',
  "L'Oréal Men Expert Hydra Energetic",
  'Axe Gel Douche Africa',
  'Bulldog Soin Visage Homme',
  'Veet Crème Dépilatoire',

  // ── Bébé ──
  'Mustela Hydra Bébé',
  'Mustela Gel Lavant Doux',
  'Mixa Bébé Crème Hydratante',
  'Nivea Baby Crème',
  'Cadum Bébé Liniment',
  'Klorane Bébé Liniment',
  'Love & Green Lingettes',
  'Bioderma ABCDerm',

  // ── Maquillage grand public ──
  'Maybelline Fit Me',
  'Maybelline Colossal Mascara',
  'Maybelline Baby Lips',
  "L'Oréal Paris Infaillible",
  "L'Oréal Paris Accord Parfait",
  "L'Oréal Volume Million Cils",
  'Gemey Maybelline Rouge à Lèvres',
  'Rimmel Wonder’Full Mascara',
  'Bourjois Healthy Mix',
  'Bourjois Rouge Velvet',
  'Max Factor Lasting Performance',
  'NYX Soft Matte Lip Cream',
  'Yves Saint Laurent Touche Éclat',
  'Essie Vernis Ballet Slippers',

  // ── Mains & divers ultra-connus ──
  'Le Chat Savon Liquide Mains',
  'Sanytol Gel Mains',
  'Neutrogena Crème Mains',
  'Yves Rocher Crème Mains Karité',
  "L'Occitane Crème Mains Karité",
  'Biafine Émulsion',
  'Bepanthen Pommade',
  'Cicalfate+ Avène',
  'Cicabiafine Baume',

  // ── Pharmacie/soin ciblé très connus ──
  'La Roche-Posay Lipikar',
  'Bioderma Atoderm Crème',
  'Avène XeraCalm',
  'Ducray Kelual DS',
  'Uriage Eau Thermale',
  'A-Derma Exomega',
  'CeraVe Baume Réparateur',
  'CeraVe Lotion Corps',
  'Eucerin UreaRepair',
  'Weleda Skin Food',
  'Klorane Masque Mangue',
  'Kérastase Bain Satin',
  'Aussie 3 Minute Miracle',
  'Garnier Bio Huile Lavande',
  'Roger & Gallet Bois d’Orange',
  'Yves Rocher Gel Lavant Mains',
  'Nivea Soft Crème',
  'Nivea Labello Fruity Shine',
  "L'Oréal Revitalift Sérum",
  'Garnier Rétinol Nuit',
  'Mixa Intensif Peaux Sèches',
  'Bioderma Cicabio',
  'La Roche-Posay Effaclar Gel',
  'Neutrogena Visibly Clear',
  'Vichy Liftactiv',
  'Nuxe Crème Fraîche de Beauté',
  'Garnier Fructis Shampooing Sec',
  'Batiste Shampooing Sec',
  'Head & Shoulders Menthol',
  'Colgate Sourire Éclatant',
  'Signal White Now',
  'Rexona Women Fraîcheur',
  'Dove Déo Invisible',
  'Nivea Deo Fresh',
  'Sanex Biome Protect',
  'Le Petit Marseillais Shampooing',
  "L'Oréal Elsève Color Vive",
  'Garnier Ultra Doux Coco',
  'Palmolive Naturals',
  'Cadum Douche Crème',
  'Dop Après-Shampooing',
  'Ushuaïa Gel Douche',
  'Tahiti Monoï',
  'Fa Sport',
  'Nivea Crème Mains',
  'Neutrogena Pieds Secs',
  'Scholl Crème Anti-Callosités',
  'Akileïne Crème Pieds',
  'Compeed Ampoules',
  'Mercurochrome',
  'Avène Cold Cream',
  'Bioderma Nodé Shampooing',
  'Klorane Shampooing Camomille',
  'René Furterer Complexe 5',
  'Franck Provost Masque Nutrition',
  'Schwarzkopf Gliss Ultimate Repair',
  'Maybelline Superstay',
  "L'Oréal Paris Elnett Laque",
  'Elnett Satin Fixation Forte',
]
